"use client";
import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { fetchExercises } from "@/app/actions/public-actions";

export default function ExerciseLibrary(){
 const [items,setItems]=useState([]),[query,setQuery]=useState(""),[category,setCategory]=useState("all"),[state,setState]=useState("loading");
 useEffect(()=>{let active=true; fetchExercises().then((r)=>{if(active){setItems(r?.allCourses||[]);setState(r?.success?"ready":"error")}}).catch(()=>active&&setState("error")); return()=>{active=false}},[]);
 const filtered=useMemo(()=>items.filter((x)=>(category==="all"||(x.category||"").toLowerCase()===category)&&(`${x.title} ${x.description}`.toLowerCase().includes(query.toLowerCase()))),[items,query,category]);
 return <section id="library" className="section-space bg-stone-50"><div className="site-container"><p className="eyebrow">Existing members</p><h2 className="mt-4 text-3xl font-black text-stone-950 sm:text-4xl">Search the exercise library</h2><p className="mt-3 max-w-2xl text-stone-600">Exercise access remains connected to your existing account and subscription entitlement.</p><div className="mt-7 grid gap-4 sm:grid-cols-[1fr_auto]"><label className="font-semibold">Search exercises<span className="sr-only"> by title or description</span><input value={query} onChange={(e)=>setQuery(e.target.value)} className="mt-2 w-full rounded-xl border border-stone-300 bg-white px-4 py-3" type="search" /></label><label className="font-semibold">Category<select value={category} onChange={(e)=>setCategory(e.target.value)} className="mt-2 block w-full rounded-xl border border-stone-300 bg-white px-4 py-3"><option value="all">All exercises</option><option value="cardio">Cardio</option><option value="strength">Strength</option><option value="flexibility">Flexibility</option><option value="balance">Balance</option></select></label></div>{state==="loading"&&<p className="mt-8" role="status">Loading exercises…</p>}{state==="error"&&<p className="mt-8 rounded-xl bg-red-50 p-4 text-red-800" role="alert">The library is temporarily unavailable. Please refresh or try again shortly.</p>}<div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{filtered.map((exercise)=><article key={exercise.id} className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="relative aspect-video bg-stone-200"><Image src={exercise.thumbnailKey} alt="" fill className="object-cover" sizes="(min-width:1024px) 30vw, 100vw" /></div><div className="p-5"><p className="text-sm font-bold uppercase tracking-wide text-rose-800">{exercise.category} · {exercise.level}</p><h3 className="mt-2 text-xl font-bold">{exercise.title}</h3><p className="mt-2 line-clamp-2 text-stone-600">{exercise.description}</p><Link className="mt-5 inline-flex rounded-full bg-rose-800 px-5 py-2.5 font-bold text-white" href={`/exercise/${exercise.id}/view`}>{exercise.isLocked?"View access options":"Start exercise"}</Link></div></article>)}</div>{state==="ready"&&filtered.length===0&&<p className="mt-8">No exercises match your search.</p>}</div></section>
}
